"""The company's document template, the same for every file the chat makes.

One look across PDF, Word and Excel: a navy header band with the company's name on every
page, a title block with the date, who it was prepared for and a reference, headings and
tables in the house colours, the sources at the end, and a footer with the page number
and a line saying the document was generated and should be checked before it is relied
on. A logo placed at data/branding/logo.png appears in the header of all three.

Only what is known is printed: the company's registered Arabic name, the reader who asked,
the date. Nothing here invents a stamp, a signature or an approval.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from app.config import BASE_DIR

COMPANY = "شركة ال يافور للنقليات والمقاولات العامة ذ.م.م"
SYSTEM_LABEL = "نظام المعرفة"
DISCLAIMER_AR = "وثيقة مُولَّدة آليًا من نظام المعرفة — تحقّق من المصادر قبل الاعتماد"
DISCLAIMER_EN = "Generated by the knowledge system — check the sources before relying on it"
LOGO = BASE_DIR / "data" / "branding" / "logo.png"

NAVY = (31, 58, 95)
GOLD = (184, 137, 59)
INK = (33, 37, 41)
MUTED = (110, 117, 125)
LIGHT = (244, 246, 249)
ZEBRA = (249, 250, 252)
RULE = (214, 219, 226)

FONT_DIR = Path(r"C:\Windows\Fonts")


def _fonts() -> tuple[Path, Path]:
    for regular, bold in (("segoeui.ttf", "segoeuib.ttf"), ("tahoma.ttf", "tahomabd.ttf"), ("arial.ttf", "arialbd.ttf")):
        if (FONT_DIR / regular).exists():
            return FONT_DIR / regular, FONT_DIR / bold if (FONT_DIR / bold).exists() else FONT_DIR / regular
    raise FileNotFoundError("No font with Arabic letters found in C:\\Windows\\Fonts")


def _hex(rgb: tuple[int, int, int]) -> str:
    return "".join(f"{c:02X}" for c in rgb)


_EMOJI = re.compile("[\U0001F000-\U0001FAFF☀-➿️]")


def _no_emoji(text: str) -> str:
    """The PDF's font has no emoji; left in, they print as nothing or as boxes."""
    return " ".join(_EMOJI.sub("", text).split())


# -- PDF -------------------------------------------------------------------

def render_pdf(content, path: Path, rtl: bool, reference: str) -> None:
    from fpdf import FPDF
    from fpdf.fonts import FontFace

    regular, bold = _fonts()
    align = "R" if rtl else "L"
    far = "L" if rtl else "R"

    class Branded(FPDF):
        def header(self) -> None:
            self.set_fill_color(*NAVY)
            self.rect(0, 0, self.w, 16, style="F")
            self.set_fill_color(*GOLD)
            self.rect(0, 16, self.w, 0.8, style="F")
            if LOGO.exists():
                self.image(str(LOGO), x=(10 if rtl else self.w - 22), y=2.5, h=11)
            self.set_text_color(255, 255, 255)
            self.set_font("brand", "B", 11.5)
            self.set_xy(10, 3.2)
            self.cell(self.w - 20, 6, COMPANY, align=align)
            self.set_font("brand", "", 8)
            self.set_xy(10, 9.2)
            self.cell(self.w - 20, 5, SYSTEM_LABEL, align=align)
            self.set_text_color(*INK)
            self.set_y(24)

        def footer(self) -> None:
            self.set_y(-14)
            self.set_draw_color(*RULE)
            self.line(10, self.get_y(), self.w - 10, self.get_y())
            self.set_font("brand", "", 7.5)
            self.set_text_color(*MUTED)
            self.set_y(-12)
            self.cell(0, 6, DISCLAIMER_AR if rtl else DISCLAIMER_EN, align=align)
            self.set_y(-12)
            self.cell(0, 6, f"{self.page_no()} / {{nb}}", align=far)
            self.set_text_color(*INK)

    pdf = Branded(format="A4")
    pdf.alias_nb_pages()
    pdf.set_margins(14, 24, 14)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_font("brand", "", str(regular))
    pdf.add_font("brand", "B", str(bold))
    pdf.set_text_shaping(use_shaping_engine=True, direction="rtl" if rtl else "ltr",
                         script="arab" if rtl else None, language="ar" if rtl else None)
    pdf.add_page()
    width = pdf.w - pdf.l_margin - pdf.r_margin

    # Title block.
    pdf.set_font("brand", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.multi_cell(width, 10, content.title, align=align, new_x="LMARGIN", new_y="NEXT")
    pdf.set_fill_color(*GOLD)
    pdf.rect(pdf.w - pdf.r_margin - 28 if rtl else pdf.l_margin, pdf.get_y() + 1, 28, 0.9, style="F")
    pdf.ln(5)
    meta = [
        ("التاريخ" if rtl else "Date", f"{datetime.now():%Y-%m-%d %H:%M}"),
        ("أُعدّ لـ" if rtl else "Prepared for", content.author or "—"),
        ("المرجع" if rtl else "Reference", reference),
        ("المصادر" if rtl else "Sources", str(len(content.sources))),
    ]
    pdf.set_font("brand", "", 8.5)
    pdf.set_fill_color(*LIGHT)
    pdf.set_draw_color(*LIGHT)
    cells = list(reversed(meta)) if rtl else meta
    column = width / len(cells)
    top = pdf.get_y()
    for index, (label, value) in enumerate(cells):
        x = pdf.l_margin + index * column
        pdf.set_xy(x, top)
        pdf.set_text_color(*MUTED)
        pdf.cell(column, 5.5, label, align="C", fill=True)
        pdf.set_xy(x, top + 5.5)
        pdf.set_text_color(*INK)
        pdf.set_font("brand", "B", 9)
        pdf.cell(column, 6.5, value[:40], align="C", fill=True)
        pdf.set_font("brand", "", 8.5)
    pdf.set_y(top + 16)

    # Body.
    for block in content.blocks:
        if block.kind == "heading":
            pdf.ln(2.5)
            pdf.set_font("brand", "B", 13.5 if block.level <= 2 else 12)
            pdf.set_text_color(*NAVY)
            pdf.multi_cell(width, 8, block.text, align=align, new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(*RULE)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(2)
            pdf.set_text_color(*INK)
        elif block.kind == "lead":
            # The direct answer, set apart so it is the first thing read.
            pdf.set_font("brand", "B", 11.5)
            pdf.set_fill_color(*LIGHT)
            pdf.set_text_color(*NAVY)
            pdf.multi_cell(width, 7.5, _no_emoji(block.text), align=align, fill=True, padding=(2.5, 3),
                           new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(*INK)
            pdf.ln(2.5)
        elif block.kind == "paragraph":
            pdf.set_font("brand", "", 10.5)
            pdf.multi_cell(width, 6.6, _no_emoji(block.text), align=align, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1.2)
        elif block.kind == "bullet":
            # The bullet drawn on its own, at the line's start — right for Arabic. Inside
            # the shaped text it landed at the far end of a right-to-left line.
            pdf.set_font("brand", "", 10.5)
            indent = 6
            top = pdf.get_y()
            pdf.set_x(pdf.l_margin + (0 if rtl else indent))
            pdf.multi_cell(width - indent, 6.4, _no_emoji(block.text), align=align, new_x="LMARGIN", new_y="NEXT")
            bottom = pdf.get_y()
            pdf.set_xy(pdf.w - pdf.r_margin - indent if rtl else pdf.l_margin, top)
            pdf.set_text_color(*GOLD)
            pdf.cell(indent, 6.4, "•", align="C")
            pdf.set_text_color(*INK)
            pdf.set_y(bottom + 0.6)
        elif block.kind == "table" and block.rows:
            pdf.ln(1.5)
            pdf.set_font("brand", "", 9)
            columns = max(len(r) for r in block.rows)
            rows = [r + [""] * (columns - len(r)) for r in block.rows]
            rows = [list(reversed(r)) for r in rows] if rtl else rows
            pdf.set_draw_color(*RULE)
            with pdf.table(
                text_align="RIGHT" if rtl else "LEFT", line_height=6.2, borders_layout="HORIZONTAL_LINES",
                headings_style=FontFace(emphasis="BOLD", color=(255, 255, 255), fill_color=NAVY),
                cell_fill_color=ZEBRA, cell_fill_mode="ROWS",
            ) as table:
                for row in rows:
                    cells_row = table.row()
                    for value in row:
                        cells_row.cell(value)
            pdf.ln(3)

    if content.note:
        pdf.ln(2)
        pdf.set_font("brand", "", 9)
        pdf.set_fill_color(253, 241, 220)
        pdf.set_text_color(122, 82, 0)
        pdf.multi_cell(width, 6, content.note, align=align, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*INK)

    if content.sources:
        pdf.ln(4)
        pdf.set_font("brand", "B", 11)
        pdf.set_text_color(*NAVY)
        pdf.multi_cell(width, 7, "المصادر" if rtl else "Sources", align=align, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(*RULE)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(1.5)
        pdf.set_font("brand", "", 8.5)
        pdf.set_text_color(*MUTED)
        for index, source in enumerate(content.sources, 1):
            pdf.multi_cell(width, 5.4, f"[{index}]  {source}", align=align, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*INK)
    pdf.output(str(path))


# -- Word ------------------------------------------------------------------

def render_docx(content, path: Path, rtl: bool, reference: str) -> None:
    from docx import Document as Docx
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Cm, Pt, RGBColor

    navy, gold, muted = RGBColor(*NAVY), RGBColor(*GOLD), RGBColor(*MUTED)
    document = Docx()
    section = document.sections[0]
    section.top_margin, section.bottom_margin = Cm(2.2), Cm(2)
    section.left_margin = section.right_margin = Cm(2)
    font_name = "Segoe UI" if (FONT_DIR / "segoeui.ttf").exists() else "Tahoma"

    normal = document.styles["Normal"]
    normal.font.name = font_name
    normal.font.size = Pt(10.5)
    normal.element.rPr.rFonts.set(qn("w:cs"), font_name)
    normal.paragraph_format.space_after = Pt(4)

    def right_to_left(paragraph) -> None:
        if not rtl:
            return
        paragraph._p.get_or_add_pPr().append(OxmlElement("w:bidi"))
        paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        for run in paragraph.runs:
            run._r.get_or_add_rPr().append(OxmlElement("w:rtl"))

    def shade(cell, rgb) -> None:
        shading = OxmlElement("w:shd")
        shading.set(qn("w:val"), "clear")
        shading.set(qn("w:fill"), _hex(rgb))
        cell._tc.get_or_add_tcPr().append(shading)

    def bottom_border(paragraph, rgb, size=12) -> None:
        borders = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        for key, value in (("w:val", "single"), ("w:sz", str(size)), ("w:space", "4"), ("w:color", _hex(rgb))):
            bottom.set(qn(key), value)
        borders.append(bottom)
        paragraph._p.get_or_add_pPr().append(borders)

    def page_field(paragraph) -> None:
        for kind, text in (("begin", None), (None, "PAGE"), ("end", None)):
            run = paragraph.add_run()
            if kind:
                field = OxmlElement("w:fldChar")
                field.set(qn("w:fldCharType"), kind)
                run._r.append(field)
            else:
                instruction = OxmlElement("w:instrText")
                instruction.set(qn("xml:space"), "preserve")
                instruction.text = text
                run._r.append(instruction)

    # Header and footer, on every page.
    header = section.header.paragraphs[0]
    if LOGO.exists():
        header.add_run().add_picture(str(LOGO), height=Cm(1.1))
        header.add_run("   ")
    name = header.add_run(COMPANY)
    name.bold, name.font.size, name.font.color.rgb = True, Pt(12), navy
    label = header.add_run(f"   |   {SYSTEM_LABEL}")
    label.font.size, label.font.color.rgb = Pt(8.5), muted
    bottom_border(header, GOLD, size=10)
    right_to_left(header)

    footer = section.footer.paragraphs[0]
    note = footer.add_run((DISCLAIMER_AR if rtl else DISCLAIMER_EN) + "   —   ")
    note.font.size, note.font.color.rgb = Pt(7.5), muted
    page_field(footer)
    right_to_left(footer)

    # Title block.
    title = document.add_paragraph()
    run = title.add_run(content.title)
    run.bold, run.font.size, run.font.color.rgb = True, Pt(20), navy
    bottom_border(title, GOLD, size=8)
    right_to_left(title)

    meta = document.add_table(rows=2, cols=4)
    meta.alignment = WD_TABLE_ALIGNMENT.CENTER
    labels = ["التاريخ", "أُعدّ لـ", "المرجع", "المصادر"] if rtl else ["Date", "Prepared for", "Reference", "Sources"]
    values = [f"{datetime.now():%Y-%m-%d %H:%M}", content.author or "—", reference, str(len(content.sources))]
    if rtl:
        meta._tbl.tblPr.append(OxmlElement("w:bidiVisual"))
    for column, (label_text, value) in enumerate(zip(labels, values)):
        for row, (text, is_label) in enumerate(((label_text, True), (value, False))):
            cell = meta.cell(row, column)
            shade(cell, LIGHT)
            paragraph = cell.paragraphs[0]
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            piece = paragraph.add_run(text)
            piece.font.size = Pt(8 if is_label else 9.5)
            piece.bold = not is_label
            piece.font.color.rgb = muted if is_label else RGBColor(*INK)
    document.add_paragraph()

    for block in content.blocks:
        if block.kind == "lead":
            paragraph = document.add_paragraph()
            piece = paragraph.add_run(block.text)
            piece.bold, piece.font.size, piece.font.color.rgb = True, Pt(12), navy
            properties = paragraph._p.get_or_add_pPr()
            shading = OxmlElement("w:shd")
            shading.set(qn("w:val"), "clear")
            shading.set(qn("w:fill"), _hex(LIGHT))
            properties.append(shading)
            paragraph.paragraph_format.space_after = Pt(10)
            right_to_left(paragraph)
            continue
        if block.kind == "heading":
            paragraph = document.add_paragraph()
            piece = paragraph.add_run(block.text)
            piece.bold, piece.font.size, piece.font.color.rgb = True, Pt(14 if block.level <= 2 else 12), navy
            paragraph.paragraph_format.space_before = Pt(10)
            bottom_border(paragraph, RULE, size=6)
            right_to_left(paragraph)
        elif block.kind == "paragraph":
            right_to_left(document.add_paragraph(block.text))
        elif block.kind == "bullet":
            right_to_left(document.add_paragraph(block.text, style="List Bullet"))
        elif block.kind == "table" and block.rows:
            columns = max(len(r) for r in block.rows)
            table = document.add_table(rows=0, cols=columns)
            table.style = "Table Grid"
            table.alignment = WD_TABLE_ALIGNMENT.CENTER
            if rtl:
                table._tbl.tblPr.append(OxmlElement("w:bidiVisual"))
            for index, row in enumerate(block.rows):
                cells = table.add_row().cells
                for column, value in enumerate(row + [""] * (columns - len(row))):
                    cells[column].text = value
                    paragraph = cells[column].paragraphs[0]
                    right_to_left(paragraph)
                    for piece in paragraph.runs:
                        piece.font.size = Pt(9.5)
                        if index == 0:
                            piece.bold = True
                            piece.font.color.rgb = RGBColor(255, 255, 255)
                    if index == 0:
                        shade(cells[column], NAVY)
                    elif index % 2 == 0:
                        shade(cells[column], ZEBRA)
            document.add_paragraph()

    if content.note:
        paragraph = document.add_paragraph()
        piece = paragraph.add_run(content.note)
        piece.font.color.rgb, piece.font.size = RGBColor(122, 82, 0), Pt(9)
        right_to_left(paragraph)
    if content.sources:
        heading = document.add_paragraph()
        piece = heading.add_run("المصادر" if rtl else "Sources")
        piece.bold, piece.font.size, piece.font.color.rgb = True, Pt(12), navy
        bottom_border(heading, RULE, size=6)
        right_to_left(heading)
        for index, source in enumerate(content.sources, 1):
            paragraph = document.add_paragraph()
            piece = paragraph.add_run(f"[{index}]  {source}")
            piece.font.size, piece.font.color.rgb = Pt(8.5), muted
            right_to_left(paragraph)
    document.save(str(path))


# -- Excel -----------------------------------------------------------------

def style_sheet(sheet, title: str, author: str, reference: str, rtl: bool, width: int) -> int:
    """The branded top of a sheet; returns the row the table starts on."""
    from openpyxl.drawing.image import Image as SheetImage
    from openpyxl.styles import Alignment, Font, PatternFill

    sheet.sheet_view.rightToLeft = rtl
    sheet.sheet_view.showGridLines = False
    last = max(width, 4)
    for row, (text, size, fill, color) in enumerate((
        (COMPANY, 14, _hex(NAVY), "FFFFFF"),
        (title, 13, None, _hex(NAVY)),
        (f"{datetime.now():%Y-%m-%d %H:%M}   ·   {author or '—'}   ·   {reference}", 9, None, _hex(MUTED)),
    ), 1):
        sheet.merge_cells(start_row=row, start_column=1, end_row=row, end_column=last)
        cell = sheet.cell(row=row, column=1, value=text)
        cell.font = Font(bold=row < 3, size=size, color=color)
        cell.alignment = Alignment(horizontal="right" if rtl else "left", vertical="center")
        if fill:
            for column in range(1, last + 1):
                sheet.cell(row=row, column=column).fill = PatternFill("solid", fgColor=fill)
    sheet.row_dimensions[1].height = 30
    sheet.row_dimensions[2].height = 24
    if LOGO.exists():
        logo = SheetImage(str(LOGO))
        logo.height, logo.width = 36, int(36 * logo.width / max(logo.height, 1))
        sheet.add_image(logo, "A1")
    # Printed: landscape, one page wide, the company and page number on every page.
    sheet.page_setup.orientation = "landscape"
    sheet.page_setup.fitToWidth = 1
    sheet.page_setup.fitToHeight = 0
    sheet.sheet_properties.pageSetUpPr.fitToPage = True
    sheet.oddHeader.right.text = COMPANY
    sheet.oddFooter.left.text = "&P / &N"
    sheet.oddFooter.right.text = DISCLAIMER_AR if rtl else DISCLAIMER_EN
    return 5
