"""The ERP integration surface.

One endpoint, deliberately not `/api/chat`. The chat route exists to serve a browser: it
returns the pipeline diagnostics the interface draws, it changes shape whenever the
interface needs something new, and it writes a learning-candidate row whenever a message
reads like someone teaching the system something. All three are right for a person and
wrong for a program. A machine caller needs a contract that is versioned, minimal and
side-effect free, and it should not quietly fill a human reviewer's queue with rows
generated by a loop.

What it does *not* do is re-implement anything. Retrieval, ranking, grounding, refusal,
conflict handling and the citation split all come from `RagService.answer()`, exactly as
the web interface gets them. This module is a door with locks on it, not a second
system: authentication, tenant binding, the limits that keep one caller from taking the
whole model, the structural refusal of web search when ERP data is present, and the
translation between the wire contract and the internal one.

Phase 1 scope. `context.erp_facts` is validated and then refused rather than accepted
and ignored — see `_reject_unsupported_context`.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import time
import uuid

from fastapi import APIRouter, Request, Response
from pydantic import ValidationError as PydanticValidationError
from starlette.concurrency import run_in_threadpool

from app.api.deps import ContainerDep
from app.exceptions import (
    IntegrationDisabledError,
    PayloadTooLargeError,
    RagTimeoutError,
    ScopeDeniedError,
    TenantMismatchError,
    UnsupportedContextError,
    ValidationError,
    WebSearchNotPermittedError,
)
from app.models.database import session_scope
from app.models.integration import IntegrationRequest
from app.schemas.chat import ChatRequest, ChatResponse
from app.schemas.integration import (
    ComputedValue,
    DocumentSource,
    ErpQueryRequest,
    ErpQueryResponse,
    KnowledgeSource,
    LatencyBreakdown,
    WebSourceRef,
)
from app.services.integration_auth import AuthenticatedClient, PresentedCredential
from app.services.integration_limits import body_fingerprint, check_quota
from app.services.live_data import needs_live_data, suggested_source
from app.services.web_search import web_search_gate

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/integrations/erp", tags=["integrations"])

ENDPOINT_PATH = "/api/v1/integrations/erp/query"
#: Phase 1 issues credentials that read approved organisational knowledge and nothing
#: narrower. Personal and team items belong to people who have accounts here; an ERP
#: user has none, so there is no identity to match them against.
PHASE_1_SCOPES = frozenset({"global"})
_SAFE_ID = re.compile(r"[^A-Za-z0-9_-]")


def _echo_id(raw: object) -> str:
    """A correlation id safe to put in a reply to an unauthenticated caller.

    Echoed so a failed call is still traceable from the other system's logs, and
    stripped first so nothing arriving from outside is reflected back verbatim.
    """
    if not isinstance(raw, str):
        return ""
    return _SAFE_ID.sub("", raw)[:64]


@router.post("/query", response_model=ErpQueryResponse)
async def erp_query(request: Request, container: ContainerDep, response: Response):
    settings = container.settings
    if not settings.integration_enabled:
        raise IntegrationDisabledError("واجهة التكامل غير مفعّلة على هذا الخادم.")

    started = time.perf_counter()

    # The raw bytes, because they are what was signed. Re-serialising a parsed object
    # and signing that would break on any difference in key order or spacing, and would
    # quietly stop verifying that the bytes on the wire were the bytes the caller sent.
    body = await request.body()
    if len(body) > settings.integration_max_body_bytes:
        raise PayloadTooLargeError(
            f"حجم الطلب يتجاوز الحد المسموح ({settings.integration_max_body_bytes} بايت)."
        )

    request.state.request_id = _echo_id(_peek_request_id(body))

    container.integration_auth.check_transport(
        request.url.scheme, request.headers.get("x-forwarded-proto", "")
    )

    presented = PresentedCredential(
        authorization=request.headers.get("authorization", ""),
        key_id_header=request.headers.get("x-rag-key-id", ""),
        timestamp=request.headers.get("x-rag-timestamp", ""),
        nonce=request.headers.get("x-rag-nonce", ""),
        signature=request.headers.get("x-rag-signature", ""),
        body=body,
    )
    idempotency_key = (request.headers.get("idempotency-key", "") or "").strip()[:128]

    client: AuthenticatedClient | None = None
    payload: ErpQueryRequest | None = None
    try:
        with session_scope() as db:
            client = container.integration_auth.authenticate(
                db, presented, method="POST", path=ENDPOINT_PATH
            )

            # Immediately after the credential is known and before anything else is
            # done with the body. Placed after validation, a caller looping on a
            # malformed request would never be slowed down: every attempt would be
            # refused by the parser before reaching the limiter, while the database took
            # the full rate of authentications. A caller stuck in a loop should be told
            # to back off, whatever is wrong with what it is sending.
            container.integration_rate_limiter.check(
                client.key_id,
                per_minute=client.rate_limit_per_minute,
                burst=client.rate_limit_burst,
            )
            check_quota(db, client.client_id, client.daily_quota)

            payload = _parse(body)
            request.state.request_id = payload.request_id

            _check_tenant(client, payload)
            _check_scopes(client, payload)
            web_allowed = _web_decision(client, payload, settings.web_search_enabled)
            _reject_unsupported_context(payload)

            if idempotency_key:
                replay = container.integration_idempotency.begin(
                    db,
                    client_id=client.client_id,
                    key=idempotency_key,
                    body_hash=body_fingerprint(body),
                )
                if replay is not None:
                    logger.info(
                        "Idempotent replay for request_id=%s key=%s",
                        payload.request_id, client.key_id,
                    )
                    response.headers["Idempotent-Replay"] = "true"
                    _audit(
                        payload, client, status_code=replay.status_code,
                        latency_ms=_ms(started), replayed=True,
                    )
                    return replay.payload
    except Exception as exc:  # noqa: BLE001 — recorded, then re-raised unchanged
        _audit_failure(request, payload, client, exc, _ms(started))
        raise

    gate = await container.integration_concurrency.acquire(
        client.key_id,
        limit=client.max_concurrency,
        queue_depth=settings.integration_queue_depth,
    )
    released = False

    try:
        chat_request = ChatRequest(
            question=payload.query,
            top_k=payload.retrieval.top_k,
            category=payload.retrieval.category,
            document_ids=payload.retrieval.document_ids or None,
        )

        def _answer() -> ChatResponse:
            # The gate is set inside the worker rather than around the await, so the
            # veto is established in the thread that will actually reach the search
            # rather than relying on how context is carried across the boundary.
            with web_search_gate(web_allowed):
                return container.rag_service.answer(chat_request, user=client.user, channel="erp")

        task = asyncio.ensure_future(run_in_threadpool(_answer))
        try:
            chat_response = await asyncio.wait_for(
                asyncio.shield(task), timeout=settings.integration_answer_budget_seconds
            )
        except (TimeoutError, asyncio.TimeoutError) as exc:
            # The generation cannot be cancelled once it is with the model, so the slot
            # stays held until it finishes. Releasing it now would let a second call
            # start against a model that is still busy with the first, which is how a
            # timeout turns into a queue.
            task.add_done_callback(lambda _: container.integration_concurrency.release(gate))
            released = True
            raise RagTimeoutError(
                "لم تكتمل الإجابة داخل المهلة المسموحة.",
                headers={"Retry-After": "5"},
            ) from exc

        result = _to_response(payload, chat_response)
        latency = _ms(started)
        result.latency_ms.total = latency

        serialised = result.model_dump(mode="json")
        with session_scope() as db:
            if idempotency_key:
                container.integration_idempotency.complete(
                    db,
                    client_id=client.client_id,
                    key=idempotency_key,
                    status_code=200,
                    payload=serialised,
                    answer_id=result.answer_id,
                )
        _audit(payload, client, status_code=200, latency_ms=latency, result=result)
        return serialised

    except Exception as exc:  # noqa: BLE001
        # A claim that produced no answer has to be let go, or every retry is told a
        # request is still running until the row expires hours from now.
        if idempotency_key:
            with session_scope() as db:
                container.integration_idempotency.abandon(
                    db, client_id=client.client_id, key=idempotency_key
                )
        _audit_failure(request, payload, client, exc, _ms(started))
        raise
    finally:
        if not released:
            container.integration_concurrency.release(gate)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _peek_request_id(body: bytes) -> object:
    """The caller's correlation id, before the body has been trusted for anything else."""
    try:
        parsed = json.loads(body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return ""
    return parsed.get("request_id", "") if isinstance(parsed, dict) else ""


def _parse(body: bytes) -> ErpQueryRequest:
    try:
        return ErpQueryRequest.model_validate_json(body)
    except PydanticValidationError as exc:
        first = exc.errors()[0] if exc.errors() else {}
        where = ".".join(str(p) for p in first.get("loc", ())) or "body"
        raise ValidationError(
            f"طلب غير صالح عند '{where}': {first.get('msg', 'قيمة غير مقبولة')}.",
            error_code="INVALID_REQUEST",
        ) from exc


def _check_tenant(client: AuthenticatedClient, payload: ErpQueryRequest) -> None:
    """Refused before retrieval, so no other tenant's data is fetched to be filtered.

    This is the whole of tenant isolation in Phase 1, and it is honest about its reach:
    there is no `tenant_id` on a document, a chunk or a section, so one instance cannot
    separate two tenants' corpora however the request is worded. What it can do is
    guarantee that a credential issued for one tenant is never served under the name of
    another — which, with one instance per tenant, is the same guarantee.
    """
    if payload.tenant_id != client.tenant_id:
        logger.warning(
            "Tenant mismatch refused: key=%s declared=%s request_id=%s",
            client.key_id, _echo_id(payload.tenant_id), payload.request_id,
        )
        raise TenantMismatchError("المستأجر المطلوب لا يطابق مفتاح التكامل.")


def _check_scopes(client: AuthenticatedClient, payload: ErpQueryRequest) -> None:
    """A request narrows what the credential may read. It can never widen it."""
    requested = {s.strip().lower() for s in payload.retrieval.knowledge_scopes if s.strip()}
    if not requested:
        return
    permitted = {s.lower() for s in client.allowed_scopes} & PHASE_1_SCOPES
    beyond = sorted(requested - permitted)
    if beyond:
        raise ScopeDeniedError(
            f"نطاقات المعرفة التالية غير مسموحة لهذا المفتاح: {', '.join(beyond)}."
        )


def _web_decision(
    client: AuthenticatedClient, payload: ErpQueryRequest, operator_enabled: bool
) -> bool:
    """Whether this one call may reach the internet.

    The refusal is structural and comes before anything else happens: a call carrying
    ERP data and asking for web search is rejected outright rather than served with the
    search quietly switched off. Serving it would leave the caller's bug in place until
    the day this check is the only thing between a supplier's prices and a public search
    engine — and the question sent to a provider is the caller's own wording, verbatim.

    Three locks, all of which must be open: the request asked, the operator allowed it
    for this credential, and the instance has web search on at all.
    """
    if payload.context.erp_facts:
        if payload.web_search_allowed:
            logger.warning(
                "Refused: web search requested on a call carrying %s ERP fact(s), key=%s",
                len(payload.context.erp_facts), client.key_id,
            )
            raise WebSearchNotPermittedError(
                "لا يجوز تفعيل البحث على الويب في طلب يحمل بيانات ERP."
            )
        return False
    return bool(payload.web_search_allowed and client.web_search_allowed and operator_enabled)


def _reject_unsupported_context(payload: ErpQueryRequest) -> None:
    """ERP facts are refused in Phase 1 rather than accepted and ignored.

    Accepting them would be the dangerous option. The caller would send live purchasing
    figures, ask whether they comply with the filed policy, and receive a confident
    answer about the policy alone — with no sign anywhere in the reply that the figures
    it named were never read. Answering from supplied live data is Phase 6 work:
    sanitising it as untrusted input, framing it in the prompt as data rather than
    instructions, reporting it in its own list, and measuring what it does to the
    context window. None of that is approved yet, so the honest reply is a refusal that
    says which phase it belongs to.

    The validation above still runs, and the web rule above still fires first, so the
    security check that matters is exercised on exactly the request that threatens it.
    """
    if payload.context.erp_facts:
        raise UnsupportedContextError(
            "تمرير context.erp_facts غير مدعوم في المرحلة الأولى؛ "
            "الإجابة من البيانات الحية ضمن نطاق مرحلة لاحقة.",
            error_code="ERP_FACTS_NOT_SUPPORTED_IN_PHASE_1",
        )


# ---------------------------------------------------------------------------
# Translation
# ---------------------------------------------------------------------------


def _to_response(payload: ErpQueryRequest, chat: ChatResponse) -> ErpQueryResponse:
    """Internal shape to wire shape. The four citation lists stay four lists."""
    answered = chat.answer_source != "none"
    timings = chat.timings_ms or {}

    warnings: list[str] = []
    conflicts: list[str] = []
    if chat.validation is not None:
        warnings = list(chat.validation.warnings)
        conflicts = list(chat.validation.conflicts)

    live = False if answered else needs_live_data(payload.query)

    return ErpQueryResponse(
        request_id=payload.request_id,
        answer_id=chat.answer_id,
        answered=answered,
        answer=chat.answer,
        answer_source=chat.answer_source,
        grounded=chat.grounded,
        language=payload.language or (chat.plan.language if chat.plan else "") or "ar",
        model=chat.model,
        latency_ms=LatencyBreakdown(
            total=timings.get("total_ms", 0),
            retrieval=timings.get("retrieval_ms"),
            generation=timings.get("generation_ms") or timings.get("web_generation_ms"),
        ),
        sources=[
            DocumentSource(
                citation=s.citation,
                document_id=s.document_id,
                filename=s.filename,
                title=s.title,
                section=s.section,
                section_path=s.section_path,
                locator=s.locator,
                page=s.page,
                version=s.version,
                category=s.category,
                tier=str(s.tier),
                score=round(s.score, 4),
                excerpt=s.excerpt,
            )
            for s in chat.sources
        ],
        knowledge_sources=[
            KnowledgeSource(
                item_id=k.item_id,
                version_id=k.version_id,
                version_no=k.version_no,
                type=k.type,
                scope=k.scope,
                content=k.content,
                source_text=k.source_text,
                confidence=k.confidence,
                influence=k.influence,
                conflicted=k.conflicted,
            )
            for k in chat.knowledge
        ],
        web_sources=[
            WebSourceRef(
                citation=w.citation,
                title=w.title,
                url=w.url,
                domain=w.domain,
                snippet=w.snippet,
                authoritative=w.authoritative,
            )
            for w in chat.web_sources
        ],
        # Nothing is supplied in Phase 1, and the list is still present rather than
        # absent: a caller that reads four lists on every reply never has to ask
        # whether a missing one means "none" or "this build does not report them".
        erp_facts_used=[],
        computed_values=[
            ComputedValue(
                kind=d.kind,
                label=d.label,
                computed=d.computed,
                stated=d.stated,
                holds=d.holds,
                difference=d.difference,
                operands=list(d.operands),
                citation=d.citation,
                locator=d.locator,
            )
            for d in chat.derived
        ],
        warnings=warnings,
        conflicts=conflicts,
        needs_live_data=live,
        suggested_source=suggested_source(payload.query) if live else None,
    )


# ---------------------------------------------------------------------------
# Audit
# ---------------------------------------------------------------------------


def _ms(since: float) -> int:
    return int((time.perf_counter() - since) * 1000)


def _audit(
    payload: ErpQueryRequest | None,
    client: AuthenticatedClient | None,
    *,
    status_code: int,
    latency_ms: int,
    error_code: str = "",
    result: ErpQueryResponse | None = None,
    replayed: bool = False,
    request_id: str = "",
) -> None:
    """One row per call, holding identifiers and counts and no content.

    No question text, no answer text, no ERP values. The answer trace already keeps the
    question under its own retention rules; copying it here would put the same sensitive
    text in a second place with a second lifetime and a second person who has to
    remember to delete it. What this row is for is the join — an ERP log line carries
    `request_id`, and from here it reaches `answer_id`, and from there the evidence.

    Never allowed to fail the call: losing the audit row must not lose the answer
    somebody is waiting for.
    """
    try:
        with session_scope() as db:
            db.add(
                IntegrationRequest(
                    id=str(uuid.uuid4()),
                    # Falls back to the id read off the raw body before it was trusted.
                    # A request refused by the parser has no parsed payload, and that is
                    # exactly the call whose correlation id somebody will come looking
                    # for — a call log that drops the id on failures traces only the
                    # requests that never needed tracing.
                    request_id=((payload.request_id if payload else "") or request_id)[:64],
                    client_id=client.client_id if client else "",
                    tenant_id=client.tenant_id if client else "",
                    external_user_id=(
                        payload.end_user.external_user_id[:64] if payload else ""
                    ),
                    endpoint=ENDPOINT_PATH,
                    status_code=status_code,
                    error_code=error_code,
                    answer_id=result.answer_id if result else "",
                    answered=bool(result.answered) if result else False,
                    answer_source=(result.answer_source if result else "") or (
                        "replay" if replayed else ""
                    ),
                    source_counts={
                        "sources": len(result.sources) if result else 0,
                        "knowledge": len(result.knowledge_sources) if result else 0,
                        "web": len(result.web_sources) if result else 0,
                        "erp_facts": len(payload.context.erp_facts) if payload else 0,
                    },
                    query_chars=len(payload.query) if payload else 0,
                    erp_fact_count=len(payload.context.erp_facts) if payload else 0,
                    latency_ms=latency_ms,
                )
            )
    except Exception:  # noqa: BLE001
        logger.exception("Could not record the integration audit row")


def _audit_failure(
    request: Request,
    payload: ErpQueryRequest | None,
    client: AuthenticatedClient | None,
    exc: Exception,
    latency_ms: int,
) -> None:
    status = int(getattr(exc, "status_code", 500) or 500)
    code = getattr(exc, "code", "") or type(exc).__name__
    echoed = getattr(request.state, "request_id", "") or ""
    logger.info(
        "Integration call failed: request_id=%s key=%s status=%s code=%s",
        echoed,
        client.key_id if client else "-",
        status,
        code,
    )
    _audit(
        payload,
        client,
        status_code=status,
        latency_ms=latency_ms,
        error_code=code[:64],
        request_id=echoed,
    )
