"""knowledge layer: items, versions, reviews, usages, candidates

Revision ID: 14b5152f17ca
Revises: 42afcd247781
Create Date: 2026-09-20 10:24:52.550436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b5152f17ca'
down_revision: Union[str, Sequence[str], None] = '42afcd247781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_version_id', sa.String(length=36), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('owner_team_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_owner_team_id'), ['owner_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_knowledge_owner_type', ['owner_user_id', 'type'], unique=False)
        batch_op.create_index('ix_knowledge_status_scope', ['status', 'scope'], unique=False)
        batch_op.create_index('ix_knowledge_type_status', ['type', 'status'], unique=False)

    op.create_table('learning_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('detected_type', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('promoted_item_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_candidates_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_candidates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_candidates_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_candidates_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_reviews_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_reviews_item_id'), ['item_id'], unique=False)

    op.create_table('knowledge_usages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('influence', sa.String(length=32), nullable=False),
    sa.Column('conflicted', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_usages_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_knowledge_usages_item_time', ['item_id', 'used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_usages_question_hash'), ['question_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_usages_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_usages_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('source_section_id', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_versions_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_knowledge_versions_item_no', ['item_id', 'version_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_versions_source_document_id'), ['source_document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_versions_source_document_id'))
        batch_op.drop_index('ix_knowledge_versions_item_no')
        batch_op.drop_index(batch_op.f('ix_knowledge_versions_item_id'))

    op.drop_table('knowledge_versions')
    with op.batch_alter_table('knowledge_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_usages_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_usages_used_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_usages_question_hash'))
        batch_op.drop_index('ix_knowledge_usages_item_time')
        batch_op.drop_index(batch_op.f('ix_knowledge_usages_item_id'))

    op.drop_table('knowledge_usages')
    with op.batch_alter_table('knowledge_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_reviews_item_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_reviews_decision'))
        batch_op.drop_index(batch_op.f('ix_knowledge_reviews_created_at'))

    op.drop_table('knowledge_reviews')
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_candidates_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_candidates_state'))
        batch_op.drop_index(batch_op.f('ix_learning_candidates_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_candidates_conversation_id'))

    op.drop_table('learning_candidates')
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_type_status')
        batch_op.drop_index('ix_knowledge_status_scope')
        batch_op.drop_index('ix_knowledge_owner_type')
        batch_op.drop_index(batch_op.f('ix_knowledge_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_scope'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_owner_team_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_department'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_created_by'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_created_at'))

    op.drop_table('knowledge_items')
    # ### end Alembic commands ###
