"""learning candidates: signal, answer link, resolution

Revision ID: 27eb1ca1cfd4
Revises: e6403bd19863
Create Date: 2026-09-20 12:43:07.063946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27eb1ca1cfd4'
down_revision: Union[str, Sequence[str], None] = 'e6403bd19863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal', sa.String(length=32), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('answer_id', sa.String(length=36), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('corrects_item_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('proposed_scope', sa.String(length=32), nullable=False, server_default='user'))
        batch_op.add_column(sa.Column('resolution_reason', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('resolved_by', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_learning_candidates_answer_id'), ['answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_candidates_corrects_item_id'), ['corrects_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_candidates_signal'), ['signal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_index(batch_op.f('ix_learning_candidates_signal'))
        batch_op.drop_index(batch_op.f('ix_learning_candidates_corrects_item_id'))
        batch_op.drop_index(batch_op.f('ix_learning_candidates_answer_id'))
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('resolution_reason')
        batch_op.drop_column('proposed_scope')
        batch_op.drop_column('corrects_item_id')
        batch_op.drop_column('answer_id')
        batch_op.drop_column('signal')

    # ### end Alembic commands ###
