"""answer traces for why-this-answer

Revision ID: 7c87bb0f440a
Revises: a70c3b0c91d2
Create Date: 2026-09-20 11:07:59.289385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c87bb0f440a'
down_revision: Union[str, Sequence[str], None] = 'a70c3b0c91d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('document_evidence', sa.JSON(), nullable=False),
    sa.Column('knowledge_used', sa.JSON(), nullable=False),
    sa.Column('policies_applied', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_conflicts', sa.Integer(), nullable=False),
    sa.Column('knowledge_layer_enabled', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_traces_question_hash'), ['question_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_traces_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_answer_traces_user_time', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_traces', schema=None) as batch_op:
        batch_op.drop_index('ix_answer_traces_user_time')
        batch_op.drop_index(batch_op.f('ix_answer_traces_user_id'))
        batch_op.drop_index(batch_op.f('ix_answer_traces_question_hash'))
        batch_op.drop_index(batch_op.f('ix_answer_traces_created_at'))

    op.drop_table('answer_traces')
    # ### end Alembic commands ###
