"""document authority metadata

Revision ID: a70c3b0c91d2
Revises: 14b5152f17ca
Create Date: 2026-09-20 11:02:50.481201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70c3b0c91d2'
down_revision: Union[str, Sequence[str], None] = '14b5152f17ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('doc_status', sa.String(length=32), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('effective_date', sa.String(length=32), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_documents_doc_status'), ['doc_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_doc_status'))
        batch_op.drop_column('effective_date')
        batch_op.drop_column('doc_status')
        batch_op.drop_column('authority')

    # ### end Alembic commands ###
