"""knowledge usage: answer id and score

Revision ID: e6403bd19863
Revises: 7c87bb0f440a
Create Date: 2026-09-20 11:09:28.190881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6403bd19863'
down_revision: Union[str, Sequence[str], None] = '7c87bb0f440a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_usages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.String(length=36), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_knowledge_usages_answer_id'), ['answer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_usages_answer_id'))
        batch_op.drop_column('score')
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###
